version: '3.3'
services:
  prom:
    build:
      context: .
      dockerfile: Dockerfile.prom
    restart: always
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
  loki:
    build:
      context: .
      dockerfile: Dockerfile.loki
    ports:
      - "3100:3100"
    # volumes: 
    #   - ../tmp/loki:/etc/loki
    command: -config.file=/etc/loki/loki-local-config.yaml
  grafana:
    image: grafana/grafana:latest
    user: "0"
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../tmp/grafana:/var/lib/grafana
    command: |
      bash -c "
      grafana-cli plugins install grafana-piechart-panel
      grafana-cli plugins install grafana-worldmap-panel
      grafana-cli plugins install grafana-clock-panel
      grafana-cli plugins install grafana-simple-json-datasource
      grafana-cli plugins install grafana-polyst
      grafana-cli admin reset-admin-password asdqwe!234
      "
    depends_on:
      - prom